### ISSUE TITLE
doesn't find any assets

### ISSUE THREAD

**Issue by sclausen** [dropwizard-bundles/dropwizard-configurable-assets-bundle#1]
Neither setting something in the settings.yml nor as a param of the new ConfiguredAssetsBundle() works. I always get a 404.

**Comment by nbauernfeind** [comment]
Haha, awesome! Thank you for letting me know; I hadn't had a chance to actually apply the jar to a real project yet. I'll get to this within a few hours.

**Comment by nbauernfeind** [comment]
Hmm, this seems to work fine for me. How are you installing the bundle?

See: https://github.com/nbauernfeind/dropwizard-test

``` bash
dropwizard-test nate$ curl localhost:8000/assets/test.txt
Test File
```

**Comment by sclausen** [comment]
I'm building with maven-shade-plugin as you, but didn't have the com.googlecode.mavennatives plugin and doesnt use scala…
And I didn't specify a resources location.
The assets are locatet in the projectfolder under client/dist and in the settings.yml I configured the assets-bundle as follows:

``` yml
assets:
  overrides:
    /assets/: /client/dist/
```

**Comment by nbauernfeind** [comment]
I just updated my sample as you say, installing the bundle with all default values and then overriding `/assets/`. But I can't reproduce your issue. The path you're using is an absolute path, maybe you intended to use `client/dist/`? 

Would you be willing to push the relevant code someplace that I could take a look at?

**Comment by sclausen** [comment]
If I change /Users/nate/ to some folder on my pc, your example wont work for me :-/
assumend a file exists in /tmp called test.html I would configure your app like

``` yml
assets:
  overrides:
     /assets/: /tmp/
```
and now making a get to http://localhost:8080/assets/test.html responds with 404.

**Comment by sclausen** [comment]
… im a little stupid … `/client/dist` to `client/dist` did the job! THX

**Comment by nbauernfeind** [comment]
=) No worries!
