### ISSUE TITLE
cache-control header is not set

### ISSUE THREAD

**Issue by carterkozak** [dropwizard-bundles/dropwizard-configurable-assets-bundle#24]
The config/servlet both store `cacheControlHeader` but it doesn't appear to be applied to responses.

**Comment by nbauernfeind** [comment]
That appears to be true! Will fix as soon as I get a few spare cycles.

**Comment by batterseapower** [comment]
This bit me too!

**Comment by nakedpony** [comment]
please look at the PR https://github.com/dropwizard-bundles/dropwizard-configurable-assets-bundle/pull/31
